### ISSUE TITLE
Not remembering password.

### ISSUE THREAD

**Issue by ajithrn** [oja/amazon-music-linux#12] opened 2018-09-02 14:28 UTC
asking for password each time open the app, seems like its not remembering the password even if select the remember password option. 

> OS info: 
Distributor ID:	Ubuntu
Description:	Pop!_OS 18.04 LTS
Release:	18.04
Codename:	bionic

**Comment by flokol120** [comment] 2018-09-02 14:57
@ajithrn I think I got it. What is your OS's language?

**Comment by ajithrn** [comment] 2018-09-03 00:13
@flokol120 en-US

**Comment by ajithrn** [comment] 2018-09-03 06:52
@flokol120 okay. i can try, but we don't use Hindi where i am from (southern part of india). so what about en-IN . the reason am using en-US is some application doesn't work well with en-IN., anyways i'll try and let you know.

**Comment by ajithrn** [comment] 2018-09-03 07:18
@flokol120 i tried, but its not working. also one other thing i notice is it wont allow me to login on the first try. but when i login again it will login successfully.

**Comment by ajithrn** [comment] 2018-09-03 08:09
@flokol120 seems like you are correct. i compiled a different version of the app, using "in" extension hard-coded in the url and not by lang variable. now its working without any issues. its remembering passwords and log me into the account first time. instead of the second try.

**Comment by flokol120** [comment] 2018-09-03 15:28
Okay then this issue will be solved by a settings page in the future. This issue is caused by #3 and #9.

**Comment by ajithrn** [comment] 2018-09-03 16:13
@flokol120 sounds like a good idea :+1:

**Comment by ajithrn** [comment] 2018-09-05 14:09
@flokol120 can we detect user location or domain using some geolocation API ? 
Like mentioned in this [Article](https://medium.com/@adeyinkaadegbenro/how-to-detect-the-location-of-your-websites-visitor-using-javascript-92f9e91c095f)

**Comment by flokol120** [comment] 2018-09-05 14:12
@ajithrn I am not a big fan of this, espacially because I use VPN, but if you can disable it, it's okay for me.

**Comment by flokol120** [comment] 2018-09-11 18:47
@ajithrn Sorry for the long absence, but I was ill. This should be fixed with the referenced commit. It would be nice if you could test it once more.

**Closed by flokol120** 2018-09-11 18:47 UTC
Labels: bug

**Comment by ajithrn** [comment] 2018-09-11 22:47
@flokol120 Its okay, i was running a modded copy for myself with hard-coded domain extension. I just updated to New version and its working great :+1:  no more issues. Thanks for your updates, and take care.

**Comment by DavidS3141** [comment] 2018-11-28 10:58
This project is amazingly simple and useful. Thanks a lot. I also just had the issue with the language settings and the password not remembering. I think it would be a good idea to explain the use of the setting in the settings bar (some additional text) as users wont make the connection between this problem and the OS language setting. I was just about to open an issue when I found this.
