### ISSUE TITLE
GUI disappears when minimised

### ISSUE THREAD

**Issue by slaybhi** [oja/amazon-music-linux#17] opened 2018-09-28 16:52 UTC
the GUI just disappears when the app is minimized, but the music plays in the background. As the GUI is not there it is not possible to modify the song or navigate.

**Comment by flokol120** [comment] 2018-09-28 21:07
@slaybhi This is not a bug. Please refer to #11. The app closes to the tray. you can open the app by clicking the icon. You can also skip/pause/play the song by right-clicking the icon. If you want an option to disable the automatic closing to tray, please open a new issue where you ask for a possibility to disable the automatic closing to the tray.

**Closed by flokol120** 2018-09-28 21:07 UTC
Labels: invalid
