### ISSUE TITLE
Browser Not Supported

### ISSUE THREAD

**Issue by reeshabhkumarranjan** [oja/amazon-music-linux#25] opened 2019-02-28 21:01 UTC
![screenshot from 2019-03-01 02-29-26](https://user-images.githubusercontent.com/25811225/53598147-fd8f4100-3bc9-11e9-93a8-b3fa439d6b0d.png)

**Comment by flokol120** [comment] 2019-03-05 19:31
Duplicate of #24.

**Closed by flokol120** 2019-03-05 19:31 UTC
